# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme
# ======================
#   Minimal Mistakes Jekyll Configuration
# ======================

minimal_mistakes_skin: "air"

# ----------------------
# Site Settings
# ----------------------
locale: "en-US"
title: "yoonie's plots"
title_separator: "-"
name: "yoonie"
description: "An amazing website."
url: "https://younisunne.github.io"
baseurl: ""
repository: "younisunne/younisunne.github.io"

# ----------------------
# Author
# ----------------------
author:
  name: "Yoonie"
  avatar:
  bio: "I am an amazing person."
  location: "Somewhere"
  email: "younisunne@email.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:younisunne@email.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/younisunne"

# ----------------------
# Footer
# ----------------------
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/younisunne"
  since: "2025"

# ----------------------
# Plugins
# ----------------------
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# ----------------------
# Pagination
# ----------------------
paginate: 5
paginate_path: /page:num/

pagination:
  debug: false
  collection: "posts"
  per_page: 10
  permalink: "/page/:num/"
  title: ":title - page :num"
  sort_field: "date"
  sort_reverse: true
  trail:
    before: 2
    after: 2

# ----------------------
# Archives
# ----------------------
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# ----------------------
# Markdown and Sass
# ----------------------
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: 1..6

sass:
  sass_dir: _sass
  style: compressed

# ----------------------
# Output
# ----------------------
permalink: /:categories/:title/
timezone: "Asia/Seoul"
encoding: "utf-8"

compress_html:
  clippings: all
  ignore:
    envs: development

# ----------------------
# Defaults
# ----------------------
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
